[settings]
experimental = true


[settings.python]
compile = false

[tools]
1password = "2.34.0"
atuin = "18.16.1"
bat = "0.26.1"
chezmoi = "2.70.5"
claude = "2.1.186"
copilot-cli = "1.0.63"
eza = "0.23.4"
fd = "10.4.2"
fzf = "0.73.1"
github-cli = "2.94.0"
jq = "1.8.2"
just = "1.53.0"
lazygit = "0.62.2"
ripgrep = "15.1.0"
starship = "1.25.1"
yq = "4.53.3"
zellij = "0.44.3"
zoxide = "0.9.9"
